version: "2"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8.0
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier

  kafka:
    image: docker.io/bitnami/kafka:3.2.3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-tier

  kafka-connect-source-twitter-api-v2:
    image: adamcc/kafka-connect-source-twitter-api-v2:0.1
    volumes:
      - "./config:/kafka-connect-source-twitter-api-v2/config"
      - "./build/libs:/kafka-connect-source-twitter-api-v2/libs"
      - "./offsets:/kafka-connect-source-twitter-api-v2/offsets"
    depends_on:
      - kafka
      - zookeeper
    networks:
      - app-tier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-tier:
    driver: bridge