version: "2"

services:
  fast-data-dev:
    image: landoop/fast-data-dev:3.3.1
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    volumes:
      - ./build/libs:/opt/landoop/connectors/third-party/kafka-connect-twitter-v2
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    networks:
      - app-tier

  kafka-connect-source-twitter-api-v2:
    image: adamcc/kafka-connect-source-twitter-api-v2:0.2
    volumes:
      - ./build/config:/kafka-connect-source-twitter-api-v2/config
      - ./offsets:/kafka-connect-source-twitter-api-v2/offsets
    depends_on:
      - fast-data-dev
    networks:
      - app-tier

  # we will use elasticsearch as one of our sinks.
  # This configuration allows you to start elasticsearch
  elasticsearch:
    image: elasticsearch:8.6.0
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
      xpack.security.http.ssl.enabled: false
      http.port: 9200
      http.cors.enabled: true
      http.cors.allow-origin: http://localhost:1358,http://127.0.0.1:1358
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: true
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - 9200:9200
      - 9300:9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    #    volumes:
    #      - ./data:/usr/share/elasticsearch/data
    networks:
      - app-tier

  # search engine
  # elasticsearch browser
  dejavu:
    image: appbaseio/dejavu:3.6.0
    container_name: dejavu
    ports:
      - 1358:1358
    links:
      - elasticsearch

  # we will use postgres as one of our sinks.
  # This configuration allows you to start postgres
  postgres:
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_USER: postgres     # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres       # define database
    ports:
      - 5432:5432                 # Postgres port
    networks:
      - app-tier

  pgadmin:
    image: dpage/pgadmin4:2023-01-13-1
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@adamcc.ch
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 5050
    ports:
      - 5050:5050
    networks:
      - app-tier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-tier:
    driver: bridge