version: "2"

services:
  fast-data-dev:
    image: landoop/fast-data-dev:3.3.1
    environment:
      ADV_HOST: 127.0.0.1
      RUNTESTS: 0
    volumes:
      - ./build/libs:/opt/landoop/connectors/third-party/kafka-connect-twitter-v2
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker
    networks:
      - app-tier

  kafka-connect-source-twitter-api-v2:
    image: adamcc/kafka-connect-source-twitter-api-v2:0.1
    volumes:
      - "./config:/kafka-connect-source-twitter-api-v2/config"
      - "./build/libs:/kafka-connect-source-twitter-api-v2/libs"
      - "./offsets:/kafka-connect-source-twitter-api-v2/offsets"
    depends_on:
      - fast-data-dev
    networks:
      - app-tier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

networks:
  app-tier:
    driver: bridge